/**
 * Change #8: PDF Report Generator
 * Core PDF generation engine using jsPDF + autotable.
 * Handles cover pages, table of contents, technical sections, charts, tables,
 * headers/footers, page numbers, and stage-specific report assembly.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { captureElementToDataURL } from './chartCapture';

// ─── Types ───────────────────────────────────────────────────

export interface ReportConfig {
    /** Project name */
    projectName: string;
    /** Well or field name */
    wellName: string;
    /** Report title */
    reportTitle: string;
    /** Report type (e.g. 'Petrophysics Report', 'Exploration Report') */
    reportType: string;
    /** Author name */
    author: string;
    /** Document number (optional) */
    documentNumber?: string;
    /** Revision string */
    revision?: string;
    /** Confidentiality classification */
    classification?: string;
    /** Company logo as data URL (optional) */
    companyLogoDataUrl?: string;
    /** Color theme accent (hex) */
    accentColor?: string;
    /** Color theme secondary */
    secondaryColor?: string;
    /** Unit system label */
    unitSystem?: 'Field' | 'Metric';
}

export interface ReportSection {
    /** Section heading (numbered, e.g. '3. Zone Summary') */
    heading: string;
    /** Body text paragraphs */
    paragraphs?: string[];
    /** Chart element refs to capture and embed */
    charts?: { element: HTMLElement; caption?: string }[];
    /** Table data for autoTable */
    tables?: {
        caption?: string;
        header: string[];
        data: (string | number)[][];
    }[];
    /** Custom HTML content (simplified) */
    customContent?: string;
}

export interface ReportDocument {
    config: ReportConfig;
    /** Executive summary (user-editable) */
    executiveSummary: string;
    sections: ReportSection[];
    /** Appendices */
    appendices?: ReportSection[];
}

// ─── Helpers ─────────────────────────────────────────────────

function formatDate(date: Date = new Date()): string {
    return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number, config: ReportConfig): void {
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.setDrawColor(200, 200, 200);

    // Thin line above footer
    doc.line(15, pageH - 15, pageW - 15, pageH - 15);

    // Left: platform tag
    doc.text('Generated by PetroStream Simulation Platform', 15, pageH - 10);

    // Center: classification
    if (config.classification) {
        doc.text(config.classification, pageW / 2, pageH - 10, { align: 'center' });
    }

    // Right: page number
    doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 15, pageH - 10, { align: 'right' });

    // Top header line with report title
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.text(config.reportTitle, pageW / 2, 8, { align: 'center' });
}

/**
 * Get the Y position immediately after the last autoTable was drawn.
 * jsPDF-autotable augments the doc instance with a `lastAutoTable` property at runtime.
 */
function getLastAutoTableY(doc: jsPDF): number {
    const last = (doc as any).lastAutoTable;
    return last?.finalY ?? 25;
}

function addSectionHeading(doc: jsPDF, heading: string, accentColor: string): void {
    const pageW = doc.internal.pageSize.getWidth();
    const currentY = getLastAutoTableY(doc) + 12;

    // Check if we need a new page
    if (currentY > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
    }

    const y = (doc as any).lastAutoTable?.finalY ? getLastAutoTableY(doc) + 12 : 25;

    // Colored left bar
    doc.setFillColor(accentColor);
    doc.rect(15, y - 6, 3, 14, 'F');

    // Heading text
    doc.setFontSize(14);
    doc.setTextColor(accentColor);
    doc.setFont('helvetica', 'bold');
    doc.text(heading, 22, y);
    doc.setFont('helvetica', 'normal');

    // Underline
    doc.setDrawColor(accentColor);
    doc.setLineWidth(0.5);
    doc.line(22, y + 2, pageW - 15, y + 2);
}

// ─── Core PDF Builder ────────────────────────────────────────

export async function generateReport(document: ReportDocument): Promise<jsPDF> {
    const { config, executiveSummary, sections, appendices } = document;
    const accentColor = config.accentColor || '#1e40af';
    const secondaryColor = config.secondaryColor || '#475569';

    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const marginX = 18;
    let totalPages = 1;

    // ─── COVER PAGE ──────────────────────────────────────
    await buildCoverPage(doc, config, accentColor);

    // ─── TABLE OF CONTENTS ───────────────────────────────
    doc.addPage();
    totalPages++;
    buildTableOfContents(doc, config, sections, appendices, accentColor);

    // ─── EXECUTIVE SUMMARY ───────────────────────────────
    doc.addPage();
    totalPages++;
    addSectionHeading(doc, '1. Executive Summary', accentColor);
    doc.setFontSize(10);
    doc.setTextColor(51, 51, 51);

    const summaryLines = doc.splitTextToSize(executiveSummary, pageW - marginX * 2);
    let textY = 35;
    for (const line of summaryLines) {
        if (textY > pageH - 20) {
            doc.addPage();
            totalPages++;
            textY = 20;
        }
        doc.text(line, marginX, textY);
        textY += 5;
    }

    // ─── TECHNICAL SECTIONS ──────────────────────────────
    let sectionNum = 2;
    for (const section of sections) {
        doc.addPage();
        totalPages++;
        addSectionHeading(doc, `${sectionNum}. ${section.heading}`, accentColor);
        sectionNum++;

        let bodyY = 35;

        // Paragraphs
        if (section.paragraphs) {
            doc.setFontSize(10);
            doc.setTextColor(51, 51, 51);
            for (const para of section.paragraphs) {
                const lines = doc.splitTextToSize(para, pageW - marginX * 2);
                for (const line of lines) {
                    if (bodyY > pageH - 25) {
                        doc.addPage();
                        totalPages++;
                        bodyY = 20;
                    }
                    doc.text(line, marginX, bodyY);
                    bodyY += 5;
                }
                bodyY += 3; // space between paragraphs
            }
        }

        // Charts
        if (section.charts) {
            for (const chart of section.charts) {
                if (bodyY > pageH - 80) {
                    doc.addPage();
                    totalPages++;
                    bodyY = 20;
                }
                try {
                    const dataUrl = await captureElementToDataURL(chart.element, {
                        scale: 1.5,
                        backgroundColor: '#ffffff',
                    });
                    const imgW = pageW - marginX * 2;
                    const imgH = (imgW * 3) / 4; // 4:3 aspect for charts
                    doc.addImage(dataUrl, 'PNG', marginX, bodyY, imgW, Math.min(imgH, 90));
                    bodyY += Math.min(imgH, 90) + 5;

                    if (chart.caption) {
                        doc.setFontSize(8);
                        doc.setTextColor(100, 100, 100);
                        doc.text(chart.caption, marginX, bodyY);
                        bodyY += 6;
                    }
                } catch (err) {
                    console.warn('Failed to capture chart for PDF:', err);
                    doc.setFontSize(9);
                    doc.setTextColor(200, 50, 50);
                    doc.text(`[Chart: ${chart.caption || 'unnamed'} - could not render]`, marginX, bodyY);
                    bodyY += 8;
                }
            }
        }

        // Tables
        if (section.tables) {
            for (const table of section.tables) {
                if (bodyY > pageH - 40) {
                    doc.addPage();
                    totalPages++;
                    bodyY = 20;
                }

                if (table.caption) {
                    doc.setFontSize(9);
                    doc.setTextColor(100, 100, 100);
                    doc.text(table.caption, marginX, bodyY);
                    bodyY += 5;
                }

                autoTable(doc, {
                    startY: bodyY,
                    head: [table.header],
                    body: table.data,
                    theme: 'grid',
                    headStyles: {
                        fillColor: accentColor,
                        textColor: '#ffffff',
                        fontStyle: 'bold',
                        fontSize: 8,
                    },
                    bodyStyles: {
                        fontSize: 8,
                        cellPadding: 2,
                    },
                    alternateRowStyles: {
                        fillColor: '#f1f5f9',
                    },
                    margin: { left: marginX, right: marginX },
                });

                bodyY = (doc as any).lastAutoTable.finalY + 8;
            }
        }
    }

    // ─── APPENDICES ──────────────────────────────────────
    if (appendices && appendices.length > 0) {
        let appendixLetter = 'A';
        for (const appendix of appendices) {
            doc.addPage();
            totalPages++;
            addSectionHeading(doc, `Appendix ${appendixLetter}: ${appendix.heading}`, secondaryColor);
            appendixLetter = String.fromCharCode(appendixLetter.charCodeAt(0) + 1);

            let appY = 35;

            if (appendix.tables) {
                for (const table of appendix.tables) {
                    autoTable(doc, {
                        startY: appY,
                        head: [table.header],
                        body: table.data,
                        theme: 'grid',
                        headStyles: {
                            fillColor: secondaryColor,
                            textColor: '#ffffff',
                            fontStyle: 'bold',
                            fontSize: 8,
                        },
                        bodyStyles: { fontSize: 8, cellPadding: 2 },
                        alternateRowStyles: { fillColor: '#f1f5f9' },
                        margin: { left: marginX, right: marginX },
                    });
                    appY = (doc as any).lastAutoTable.finalY + 8;
                }
            }
        }
    }

    // ─── DISCLAIMER FOOTER ON LAST PAGE ─────────────────
    const lastPageObj = doc.internal.pages[doc.internal.pages.length - 1];
    if (lastPageObj) {
        doc.setPage(doc.internal.pages.length);
        doc.setFontSize(7);
        doc.setTextColor(160, 160, 160);
        const timestamp = new Date().toISOString();
        doc.text(
            `Report generated by PetroStream Simulation Platform | ${timestamp}`,
            pageW / 2,
            pageH - 10,
            { align: 'center' }
        );
    }

    // ─── ADD PAGE FOOTERS TO ALL PAGES ──────────────────
    const finalTotalPages = doc.internal.pages.length;
    for (let i = 1; i <= finalTotalPages; i++) {
        doc.setPage(i);
        addFooter(doc, i, finalTotalPages, config);
    }

    return doc;
}

// ─── Cover Page Builder ──────────────────────────────────────

async function buildCoverPage(doc: jsPDF, config: ReportConfig, accentColor: string): Promise<void> {
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();

    // Background accent bar at top
    doc.setFillColor(accentColor);
    doc.rect(0, 0, pageW, 60, 'F');

    // Secondary bar
    doc.setFillColor('#334155');
    doc.rect(0, 60, pageW, 4, 'F');

    // Company logo (top left of colored bar)
    if (config.companyLogoDataUrl) {
        try {
            doc.addImage(config.companyLogoDataUrl, 'PNG', 15, 8, 44, 44);
        } catch {
            // Logo failed, continue without
        }
    }

    // Report type label (top right of colored bar)
    doc.setFontSize(12);
    doc.setTextColor('#ffffff');
    doc.setFont('helvetica', 'bold');
    doc.text(config.reportType.toUpperCase(), pageW - 15, 25, { align: 'right' });

    // Document info below top bar
    doc.setFontSize(9);
    doc.setTextColor('#cbd5e1');
    doc.setFont('helvetica', 'normal');
    if (config.documentNumber) {
        doc.text(`Doc No: ${config.documentNumber}`, pageW - 15, 35, { align: 'right' });
    }
    doc.text(`Rev: ${config.revision || '01'}`, pageW - 15, 40, { align: 'right' });
    if (config.classification) {
        doc.text(config.classification, pageW - 15, 45, { align: 'right' });
    }

    // Main title block
    const titleY = 90;
    doc.setFontSize(24);
    doc.setTextColor(accentColor);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(config.reportTitle, pageW - 40);
    doc.text(titleLines, 20, titleY);

    // Subtitle / project info
    doc.setFontSize(14);
    doc.setTextColor('#475569');
    doc.setFont('helvetica', 'normal');
    doc.text(`Project: ${config.projectName}`, 20, titleY + 18);

    doc.setFontSize(12);
    doc.text(`Well / Field: ${config.wellName}`, 20, titleY + 28);

    // Info block (lower center)
    const infoY = 155;
    doc.setFontSize(10);
    doc.setTextColor('#334155');

    const infoLines = [
        `Author: ${config.author}`,
        `Date: ${formatDate()}`,
        `Unit System: ${config.unitSystem || 'Field'}`,
        `Software: PetroStream Simulation Platform`,
    ];

    infoLines.forEach((line, i) => {
        doc.text(line, 20, infoY + i * 8);
    });

    // Bottom accent line
    doc.setFillColor(accentColor);
    doc.rect(0, pageH - 8, pageW, 8, 'F');

    // Disclaimer
    doc.setFontSize(7);
    doc.setTextColor('#94a3b8');
    doc.text(
        'This report was generated using PetroStream Simulation Platform and is intended for technical reference.',
        pageW / 2,
        pageH - 2,
        { align: 'center' }
    );
}

// ─── Table of Contents Builder ───────────────────────────────

function buildTableOfContents(
    doc: jsPDF,
    _config: ReportConfig,
    sections: ReportSection[],
    appendices?: ReportSection[],
    accentColor?: string
): void {
    const pageW = doc.internal.pageSize.getWidth();
    const headingColor = accentColor || '#1e40af';

    doc.setFontSize(18);
    doc.setTextColor(headingColor);
    doc.setFont('helvetica', 'bold');
    doc.text('Table of Contents', pageW / 2, 30, { align: 'center' });

    let tocY = 45;
    const leftMargin = 25;
    let pageNum = 3; // After cover + TOC = page 3 for first section

    // Executive Summary
    doc.setFontSize(11);
    doc.setTextColor(51, 51, 51);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Executive Summary', leftMargin, tocY);
    doc.text('2', pageW - 25, tocY, { align: 'right' });
    tocY += 8;

    // Technical sections
    let sectionNum = 2;
    for (const section of sections) {
        doc.setFont('helvetica', 'bold');
        doc.text(`${sectionNum}. ${section.heading}`, leftMargin, tocY);

        // Dots leader (simplified)
        doc.setFont('helvetica', 'normal');
        doc.text('. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .', leftMargin + 60, tocY);
        doc.text(String(pageNum), pageW - 25, tocY, { align: 'right' });

        tocY += 7;
        sectionNum++;
        pageNum++; // Each section starts on a new page
    }

    // Appendices
    if (appendices && appendices.length > 0) {
        tocY += 5;
        doc.setFontSize(12);
        doc.setTextColor(headingColor);
        doc.text('Appendices', leftMargin, tocY);
        tocY += 8;

        let appLetter = 'A';
        for (const appendix of appendices) {
            doc.setFontSize(10);
            doc.setTextColor(51, 51, 51);
            doc.setFont('helvetica', 'normal');
            doc.text(`Appendix ${appLetter}: ${appendix.heading}`, leftMargin + 5, tocY);
            doc.text(String(pageNum), pageW - 25, tocY, { align: 'right' });
            tocY += 7;
            appLetter = String.fromCharCode(appLetter.charCodeAt(0) + 1);
            pageNum++;
        }
    }
}

// ─── Quick Export Helper ─────────────────────────────────────

/**
 * Generates and triggers a PDF download from a ReportDocument.
 */
export async function downloadReport(document: ReportDocument, filename?: string): Promise<void> {
    const doc = await generateReport(document);
    const name =
        filename ||
        `PetroStream_${document.config.reportType.replace(/\s+/g, '_')}_${document.config.wellName.replace(/\s+/g, '_')}.pdf`;
    doc.save(name);
}

/**
 * Returns the PDF as a Blob (for server upload or preview).
 */
export async function reportToBlob(document: ReportDocument): Promise<Blob> {
    const doc = await generateReport(document);
    return doc.output('blob');
}

/**
 * Returns the PDF as a data URL (for preview).
 */
export async function reportToDataUrl(document: ReportDocument): Promise<string> {
    const doc = await generateReport(document);
    return doc.output('dataurlstring');
}