import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ShieldCheck, 
  AlertTriangle, 
  Flame, 
  Activity, 
  Thermometer, 
  Globe, 
  Leaf,
  LayoutDashboard,
  Shield,
  Zap,
  Box,
  Heart,
  Wind,
  Database
} from 'lucide-react';
import { cn } from '../../lib/utils';
import { Loader2, Download, CheckCircle2 } from 'lucide-react';

type HSETab = 
  | 'ph1' | 'ph2' | 'ph3' | 'ph4' | 'ph5' | 'ph6' | 'ph7';

export default function HSEAdvStage() {
  const [activeTab, setActiveTab] = useState<HSETab>('ph1');
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportReady, setReportReady] = useState(false);

  const tabs = [
    { id: 'ph1' as HSETab, label: 'Ph.1: Safety Systems', icon: ShieldCheck },
    { id: 'ph2' as HSETab, label: 'Ph.2: Hazard ID', icon: AlertTriangle },
    { id: 'ph3' as HSETab, label: 'Ph.3: Process Safety', icon: Shield },
    { id: 'ph4' as HSETab, label: 'Ph.4: Emergency', icon: Flame },
    { id: 'ph5' as HSETab, label: 'Ph.5: Health', icon: Heart },
    { id: 'ph6' as HSETab, label: 'Ph.6: Environmental', icon: Leaf },
    { id: 'ph7' as HSETab, label: 'Ph.7: ESG', icon: Globe },
  ];

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setReportReady(false);
    
    // Simulate a real file download in the browser
    setTimeout(() => {
      setIsGenerating(false);
      setReportReady(true);
      
      const element = document.createElement("a");
      const file = new Blob(["PetroStream HSE Compliance Report - 2024\n\nTRIR: 0.12\nCarbon Intensity: 9.4 kg/boe\nMethane Leakage: 0.12%\nCompliance Score: 98.2%\n\nGenerated by AstraCore Intelligence Systems."], {type: 'text/plain'});
      element.href = URL.createObjectURL(file);
      element.download = "HSE_Compliance_Report.txt";
      document.body.appendChild(element);
      element.click();
    }, 3000);
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex flex-wrap items-center gap-2 px-6 py-4 border-b border-white/5 bg-black/20">
        <ShieldCheck className="text-emerald-500" size={20} />
        <span className="text-white font-black italic text-lg tracking-tight mr-6 uppercase">Advanced HSE & Sustainability</span>
        {tabs.map(t => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id)}
            className={cn(
              'flex items-center gap-2 px-5 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all',
              activeTab === t.id
                ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-500/20'
                : 'text-slate-500 hover:text-white hover:bg-white/5'
            )}
          >
            <t.icon size={13} />{t.label}
          </button>
        ))}
        
        <div className="ml-auto">
           <button
             onClick={handleGenerateReport}
             disabled={isGenerating}
             className={cn(
               "flex items-center gap-3 px-6 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all border",
               reportReady 
                ? "bg-emerald-500/20 border-emerald-500 text-emerald-400" 
                : "bg-white/5 border-white/10 text-white hover:bg-white/10"
             )}
           >
             {isGenerating ? <Loader2 size={14} className="animate-spin" /> : reportReady ? <CheckCircle2 size={14} /> : <Download size={14} />}
             {isGenerating ? "Compiling Report..." : reportReady ? "Report Downloaded" : "Generate Compliance Report"}
           </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 1.02 }}
            transition={{ duration: 0.2 }}
            className="h-full"
          >
            {activeTab === 'ph1' && <Phase1SafetySystems />}
            {activeTab === 'ph2' && <Phase2HazardID />}
            {activeTab === 'ph3' && <Phase3ProcessSafety />}
            {activeTab === 'ph4' && <Phase4Emergency />}
            {activeTab === 'ph5' && <Phase5Health />}
            {activeTab === 'ph6' && <Phase6Environmental />}
            {activeTab === 'ph7' && <Phase7ESG />}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}

// ─── Phase Components ────────────────────────────────────────────────────────

function Phase1SafetySystems() {
  const safetyPerformance = [
    { month: 'JAN', trir: 0.25, lti: 0 },
    { month: 'FEB', trir: 0.32, lti: 0 },
    { month: 'MAR', trir: 0.28, lti: 1 },
    { month: 'APR', trir: 0.15, lti: 0 },
    { month: 'MAY', trir: 0.12, lti: 0 },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <ShieldCheck className="text-emerald-500" size={36} />
             Phase 1: Safety <span className="text-emerald-500/50">Systems</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">SEMS · ISO 45001 · OSHA PSM · Safety Case</p>
        </div>
        <div className="text-right">
           <p className="text-3xl font-black text-emerald-500 italic">0.12</p>
           <p className="text-[11px] text-slate-500 uppercase font-bold">Total Recordable Injury Rate (TRIR)</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[400px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  Monthly Safety Performance (TRIR Trend)
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <SafetyShield3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center text-center">
               <Zap size={48} className="text-emerald-500 mx-auto mb-4" />
               <h4 className="text-xs font-black text-white uppercase italic mb-2">Safety Culture Index</h4>
               <p className="text-4xl font-black text-white italic tracking-tighter mb-2">9.4</p>
               <div className="px-3 py-1 bg-emerald-500/10 rounded-full border border-emerald-500/20 inline-block mx-auto">
                  <span className="text-[10px] font-black text-emerald-500 uppercase tracking-widest italic">PREVENTATIVE MATURITY</span>
               </div>
            </div>
         </div>
      </div>
    </div>
  );
}

function Phase2HazardID() {
  const hazardHeat = [
    { x: 1, y: 1, z: 10, name: 'Trivial' },
    { x: 2, y: 4, z: 85, name: 'Critical' },
    { x: 4, y: 2, z: 35, name: 'Moderate' },
    { x: 5, y: 5, z: 95, name: 'Extreme' },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <AlertTriangle className="text-emerald-500" size={36} />
             Phase 2: Hazard ID <span className="text-emerald-500/50">& Risk Assessment</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">HAZOP · LOPA · QRA · ALARP · SIL</p>
        </div>
        <div className="px-6 py-2 bg-rose-500/10 border border-rose-500/20 rounded-2xl">
           <span className="text-[10px] font-black text-rose-500 uppercase tracking-widest">ALARP STATUS: CRITICAL</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[400px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  Risk Exposure Heatmap (Prob vs. Severity)
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <HazardRadar3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center text-center">
               <Box size={48} className="text-emerald-500 mx-auto mb-4" />
               <h4 className="text-xs font-black text-white uppercase italic mb-2">Open Action Items</h4>
               <p className="text-5xl font-black text-white italic tracking-tighter mb-2">14</p>
               <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest italic leading-relaxed">
                  Active Mitigation Requirements
               </p>
            </div>
         </div>
      </div>
    </div>
  );
}

function Phase3ProcessSafety() {
  const pspiData = [
    { year: '2020', t1: 2, t2: 8 },
    { year: '2021', t1: 1, t2: 5 },
    { year: '2022', t1: 0, t2: 4 },
    { year: '2023', t1: 0, t2: 2 },
    { year: '2024', t1: 0, t2: 1 },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <Shield className="text-emerald-500" size={36} />
             Phase 3: <span className="text-emerald-500/50">Process Safety</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">MAH · Tier 1/2 KPIs · MOC · Barrier Integrity</p>
        </div>
        <div className="text-right">
           <p className="text-3xl font-black text-emerald-500 italic">TIER 1: 0</p>
           <p className="text-[11px] text-slate-500 uppercase font-bold">Process Safety Incidents (YTD)</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[400px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  Process Safety Performance Indicators (Tier 1 & 2)
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <BarrierNetwork3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center text-center">
               <Shield size={48} className="text-emerald-500 mx-auto mb-4" />
               <h4 className="text-xs font-black text-white uppercase italic mb-2">Barrier Integrity</h4>
               <p className="text-4xl font-black text-white italic tracking-tighter mb-2">99.8%</p>
               <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest italic">Safety Critical Elements (SCE)</p>
            </div>
         </div>
      </div>
    </div>
  );
}

function Phase4Emergency() {
  const readinessTrend = [
    { name: 'Drill 1', score: 78, time: 12 },
    { name: 'Drill 2', score: 85, time: 10 },
    { name: 'Drill 3', score: 92, time: 8 },
    { name: 'Drill 4', score: 88, time: 9 },
    { name: 'Drill 5', score: 96, time: 7 },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <Flame className="text-emerald-500" size={36} />
             Phase 4: <span className="text-emerald-500/50">Emergency Response</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">ERP · OSRP · Incident Command · Readiness</p>
        </div>
        <div className="text-right">
           <p className="text-3xl font-black text-emerald-500 italic">7.2 <span className="text-sm">min</span></p>
           <p className="text-[11px] text-slate-500 uppercase font-bold">Average Response Time</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[400px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  Drill Effectiveness & Response Time Trend
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <ResponseCenter3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center text-center">
               <Shield size={48} className="text-emerald-500 mx-auto mb-4" />
               <h4 className="text-xs font-black text-white uppercase italic mb-2">Readiness Level</h4>
               <p className="text-4xl font-black text-white italic tracking-tighter mb-2">GOLD</p>
               <div className="px-3 py-1 bg-emerald-500/10 rounded-full border border-emerald-500/20 inline-block mx-auto">
                  <span className="text-[10px] font-black text-emerald-500 uppercase tracking-widest italic">TIER 3 CAPABILITY ACTIVE</span>
               </div>
            </div>
         </div>
      </div>
    </div>
  );
}

function Phase5Health() {
  const healthExposure = [
    { subject: 'H2S', A: 45, fullMark: 100 },
    { subject: 'Noise', A: 82, fullMark: 100 },
    { subject: 'Benzene', A: 30, fullMark: 100 },
    { subject: 'Heat', A: 65, fullMark: 100 },
    { subject: 'NORM', A: 15, fullMark: 100 },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <Heart className="text-emerald-500" size={36} />
             Phase 5: <span className="text-emerald-500/50">Occupational Health</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">H2S · NORM · Benzene · Noise · Hygiene</p>
        </div>
        <div className="text-right">
           <p className="text-3xl font-black text-white italic">94.8%</p>
           <p className="text-[11px] text-slate-500 uppercase font-bold">Health Compliance Score</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[450px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  Workforce Exposure Matrix (Industrial Hygiene)
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <VitalsSphere3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center text-center">
               <ShieldCheck size={48} className="text-emerald-500 mx-auto mb-4" />
               <h4 className="text-xs font-black text-white uppercase italic mb-2">PPE Compliance</h4>
               <p className="text-4xl font-black text-emerald-400 italic tracking-tighter mb-2">100%</p>
               <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest leading-relaxed">
                  Active Monitoring Systems Synchronized
               </p>
            </div>
         </div>
      </div>
    </div>
  );
}

function Phase6Environmental() {
  const emissionData = [
    { year: '2021', intensity: 18.5 },
    { year: '2022', intensity: 15.2 },
    { year: '2023', intensity: 12.8 },
    { year: '2024', intensity: 9.4 },
    { year: '2025', intensity: 7.2 },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <Leaf className="text-emerald-500" size={36} />
             Phase 6: <span className="text-emerald-500/50">Environmental</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">EIA · Emissions · Water · Waste · Reclamation</p>
        </div>
        <div className="text-right">
           <p className="text-3xl font-black text-emerald-500 italic">98.2%</p>
           <p className="text-[11px] text-slate-500 uppercase font-bold">LDAR Compliance Rate</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[400px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Activity size={16} className="text-emerald-500" />
                  Carbon Intensity Reduction Profile (kgCO2e/boe)
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <EcoImpact3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center text-center">
               <Wind size={48} className="text-emerald-500 mx-auto mb-4" />
               <h4 className="text-xs font-black text-white uppercase italic mb-2">Methane Leakage</h4>
               <p className="text-4xl font-black text-white italic tracking-tighter mb-2">0.12%</p>
               <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">OGMP 2.0 Gold Standard</p>
            </div>
         </div>
      </div>
    </div>
  );
}

function Phase7ESG() {
  const esgMix = [
    { name: 'Scope 1', val: 55, color: '#10b981' },
    { name: 'Scope 2', val: 25, color: '#059669' },
    { name: 'Scope 3', val: 20, color: '#065f46' },
  ];

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end">
        <div>
           <h2 className="text-4xl font-black text-white italic tracking-tighter flex items-center gap-3">
             <Globe className="text-emerald-500" size={36} />
             Phase 7: ESG <span className="text-emerald-500/50">& Sustainability</span>
           </h2>
           <p className="text-slate-500 text-sm mt-2 font-medium uppercase tracking-widest">GHG Scope 1-3 · TCFD · GRI · Community</p>
        </div>
        <div className="text-right">
           <p className="text-3xl font-black text-emerald-500 italic">AA+</p>
           <p className="text-[11px] text-slate-500 uppercase font-bold">MSCI Sustainability Rating</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         <div className="lg:col-span-8">
            <div className="glass-card p-10 rounded-3xl bg-black/40 border-white/5 h-[450px]">
               <h3 className="text-sm font-black text-white uppercase tracking-widest italic mb-8 flex items-center gap-2">
                  <Database size={16} className="text-emerald-500" />
                  GHG Emission Distribution (Scope 1-3)
               </h3>
               <div className="h-[300px] flex items-center justify-center">
                  <SustainabilityPillar3D />
               </div>
            </div>
         </div>
         <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="glass-card p-8 rounded-3xl bg-emerald-500/5 border-emerald-500/10 flex-1 flex flex-col justify-center">
               <h4 className="text-xs font-black text-white uppercase italic mb-6 text-center">Disclosure Status</h4>
               <div className="space-y-4">
                  <div className="flex justify-between items-center px-4 py-3 bg-black/20 rounded-2xl border border-white/5">
                     <span className="text-[10px] text-slate-500 font-bold uppercase">TCFD Alignment</span>
                     <span className="text-emerald-400 font-black italic text-lg">100%</span>
                  </div>
                  <div className="flex justify-between items-center px-4 py-3 bg-black/20 rounded-2xl border border-white/5">
                     <span className="text-[10px] text-slate-500 font-bold uppercase">GRI Index</span>
                     <span className="text-white font-black italic text-lg">94.5</span>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </div>
  );
}

// ─── 3D Visualizer Components ──────────────────────────────────────────────

function SafetyShield3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        {/* Isometric Shield Layers */}
        {[0, 1, 2].map(i => (
          <motion.path 
            key={i}
            d={`M 250 ${50 + i*30} L 150 ${100 + i*30} V 200 L 250 250 L 350 200 V 100 Z`}
            fill="none" stroke="#10b981" strokeWidth="2" strokeOpacity={0.1 + i*0.2}
            animate={{ scale: [1, 1.05, 1], opacity: [0.2, 0.5, 0.2] }}
            transition={{ repeat: Infinity, duration: 4, delay: i*0.5 }}
          />
        ))}
        {/* Defense Rings */}
        <motion.circle 
          cx="250" cy="150" r="40" fill="none" stroke="#10b981" strokeWidth="1" strokeDasharray="4 2"
          animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 10, ease: "linear" }}
        />
        <text x="250" y="280" fill="#10b981" fontSize="10" textAnchor="middle" className="font-black uppercase tracking-widest italic">Multi-Layer Defense System</text>
      </svg>
    </div>
  );
}

function HazardRadar3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        {/* Isometric Radar Field */}
        <path d="M 50 150 L 250 50 L 450 150 L 250 250 Z" fill="#0f172a" stroke="#10b981" strokeWidth="1" strokeOpacity="0.2" />
        {/* Scanning Beam */}
        <motion.line 
          x1="250" y1="150" x2="450" y2="150" stroke="#10b981" strokeWidth="2"
          animate={{ rotate: [0, 360] }}
          style={{ originX: '250px', originY: '150px' }}
          transition={{ repeat: Infinity, duration: 4, ease: "linear" }}
        />
        {/* Hazard Nodes */}
        {[
          { x: 150, y: 120, color: '#f43f5e' },
          { x: 350, y: 100, color: '#fbbf24' },
          { x: 300, y: 200, color: '#10b981' }
        ].map((h, i) => (
          <motion.circle 
            key={i} cx={h.x} cy={h.y} r="6" fill={h.color}
            initial={{ scale: 0 }} animate={{ scale: [0, 1.5, 1], opacity: [0, 1, 0.8] }}
            transition={{ repeat: Infinity, duration: 3, delay: i*1 }}
          />
        ))}
      </svg>
    </div>
  );
}

function BarrierNetwork3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        {/* Isometric Barrier Pipe */}
        <path d="M 100 150 H 400" stroke="#1e293b" strokeWidth="20" strokeLinecap="round" />
        {[150, 250, 350].map((x, i) => (
          <g key={i}>
            <rect x={x-10} y="130" width="20" height="40" fill="#0f172a" stroke="#10b981" strokeWidth="2" rx="4" />
            <motion.circle 
              cx={x} cy="150" r="4" fill="#10b981"
              animate={{ fillOpacity: [0.2, 1, 0.2] }}
              transition={{ repeat: Infinity, duration: 2, delay: i*0.5 }}
            />
          </g>
        ))}
        {/* Flow particles */}
        {[0, 1, 2].map(i => (
          <motion.circle 
            key={i} r="3" fill="#10b981"
            animate={{ x: [100, 400], opacity: [0, 1, 0] }}
            transition={{ repeat: Infinity, duration: 3, delay: i*1, ease: "linear" }}
            cy="150"
          />
        ))}
      </svg>
    </div>
  );
}

function ResponseCenter3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        <path d="M 50 150 L 250 50 L 450 150 L 250 250 Z" fill="#0f172a" stroke="#10b981" strokeWidth="1" strokeOpacity="0.1" />
        {[
          { x: 150, y: 130, label: 'EMT' },
          { x: 350, y: 120, label: 'FIRE' },
          { x: 250, y: 180, label: 'HQ' }
        ].map((p, i) => (
          <g key={i}>
            <motion.path 
              d={`M ${p.x} ${p.y} L ${p.x+10} ${p.y-20} L ${p.x+20} ${p.y} Z`}
              fill="#10b981"
              animate={{ y: [0, -10, 0] }}
              transition={{ repeat: Infinity, duration: 2, delay: i*0.3 }}
            />
            <text x={p.x+10} y={p.y+15} fill="#64748b" fontSize="8" textAnchor="middle" className="font-black uppercase italic">{p.label}</text>
          </g>
        ))}
        {/* Dispatch lines */}
        <motion.path 
          d="M 250 180 L 150 130 M 250 180 L 350 120" stroke="#10b981" strokeWidth="1" strokeDasharray="4 2"
          animate={{ strokeDashoffset: -20 }} transition={{ repeat: Infinity, duration: 2, ease: "linear" }}
        />
      </svg>
    </div>
  );
}

function VitalsSphere3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        <defs>
          <radialGradient id="sphereGrad" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#10b981" stopOpacity="0.2" />
            <stop offset="100%" stopColor="#10b981" stopOpacity="0" />
          </radialGradient>
        </defs>
        <circle cx="250" cy="150" r="100" fill="url(#sphereGrad)" stroke="#10b981" strokeWidth="1" strokeOpacity="0.2" />
        {[0, 1, 2, 3].map(i => (
          <motion.path 
            key={i}
            d="M 150 150 Q 250 50 350 150 Q 250 250 150 150"
            fill="none" stroke="#10b981" strokeWidth="1" strokeOpacity={0.3}
            animate={{ rotate: i * 45 }}
            style={{ originX: '250px', originY: '150px' }}
          />
        ))}
        <motion.circle 
          cx="250" cy="150" r="5" fill="#10b981"
          animate={{ scale: [1, 1.5, 1], fillOpacity: [0.5, 1, 0.5] }}
          transition={{ repeat: Infinity, duration: 1 }}
        />
      </svg>
    </div>
  );
}

function EcoImpact3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        {/* Isometric Soil Block */}
        <path d="M 100 150 L 250 80 L 400 150 L 250 220 Z" fill="#0f172a" stroke="#10b981" strokeWidth="2" />
        <path d="M 100 150 V 200 L 250 270 V 220 Z" fill="#0f172a" stroke="#059669" strokeWidth="2" />
        <path d="M 400 150 V 200 L 250 270 V 220 Z" fill="#0f172a" stroke="#065f46" strokeWidth="2" />
        
        {/* Flora/Fauna nodes */}
        {[180, 250, 320].map((x, i) => (
          <motion.path 
            key={i} d={`M ${x} ${150-i*10} L ${x+5} ${130-i*10} L ${x+10} ${150-i*10} Z`}
            fill="#10b981"
            animate={{ scaleY: [1, 1.2, 1] }}
            transition={{ repeat: Infinity, duration: 3, delay: i*0.5 }}
          />
        ))}
      </svg>
    </div>
  );
}

function SustainabilityPillar3D() {
  return (
    <div className="w-full h-full max-w-[500px]">
      <svg viewBox="0 0 500 300" className="w-full h-full">
        {[
          { x: 100, h: 180, label: 'ENV', color: '#10b981' },
          { x: 250, h: 220, label: 'SOC', color: '#059669' },
          { x: 400, h: 200, label: 'GOV', color: '#064e3b' }
        ].map((p, i) => (
          <g key={i}>
            <motion.path 
              d={`M ${p.x} 250 L ${p.x+40} 230 L ${p.x+80} 250 L ${p.x+40} 270 Z`}
              fill="#0f172a" stroke={p.color} strokeWidth="2"
            />
            <motion.rect 
              x={p.x} y={250 - p.h} width="80" height={p.h} fill={p.color} fillOpacity="0.2" stroke={p.color} strokeWidth="2"
              initial={{ height: 0, y: 250 }} animate={{ height: p.h, y: 250 - p.h }} transition={{ duration: 1.5, delay: i*0.3 }}
            />
            <text x={p.x+40} y={285} fill={p.color} fontSize="10" textAnchor="middle" className="font-black italic uppercase">{p.label}</text>
          </g>
        ))}
      </svg>
    </div>
  );
}

function DetailCard({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="glass-card p-6 rounded-3xl border-white/5 bg-emerald-500/5 hover:border-emerald-500/30 transition-all">
      <h5 className="text-[11px] font-black uppercase tracking-widest text-emerald-500 mb-4">{title}</h5>
      <ul className="space-y-3">
        {items.map((item, idx) => (
          <li key={idx} className="flex items-start gap-3">
            <div className="mt-1.5 w-1 h-1 rounded-full bg-emerald-500 shrink-0" />
            <span className="text-[11px] text-slate-300 leading-relaxed font-medium">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
